version: "3.9"  # optional since v1.27.0
services:
  api:
    build: .
    ports:
      - "8000:8000"
    links:
      - redis

  redis:
    image: redis
  
  angular:
    build:
      context: frontend
    image: angular-app
    ports:
      - 3000:3000
  